# Generated by Django 4.2.7 on 2023-12-06 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('sensibilidad', models.DecimalField(decimal_places=1, max_digits=3)),
                ('umbral_alarma', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Dato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('concentracion_humo', models.DecimalField(decimal_places=1, max_digits=3)),
                ('concentracion_gases', models.DecimalField(decimal_places=1, max_digits=3)),
                ('detector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appfirefly.detector')),
            ],
        ),
        migrations.CreateModel(
            name='Alarma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('tipo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('detector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appfirefly.detector')),
            ],
        ),
    ]
