# Generated by Django 4.2.7 on 2023-12-06 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfirefly', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dato',
            name='concentracion_humo',
        ),
        migrations.RemoveField(
            model_name='dato',
            name='detector',
        ),
    ]
